import { Global } from '../global';
import { Mongoose } from 'mongoose';
import express from 'express';
import Yup from 'yup';
declare const setMiddleware: (app: express.Application, setMiddle: Global.setMiddleware[]) => Promise<void>;
declare const useMiddleware: (app: express.Application, useMiddle: any[]) => Promise<void>;
declare const establishConnection: (username: string, password: string) => Promise<void>;
declare const save: (data: Global.URL, model: Mongoose['Model'], validator: Yup.ObjectSchema) => Promise<void>;
declare const find: (id: string, model: Mongoose['Model']) => Promise<unknown>;
declare const remove: (id: string, model: Mongoose['Model']) => Promise<unknown>;
export { setMiddleware, useMiddleware, establishConnection, save, find, remove };
